name: DevOps Engineering Test

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: unittest
  displayName: 'Run unittest'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9.19'
      addToPath: true
  - script: |
      pip install pytest==8.1.1
      python -m pytest unittest/test.py

- job: build_and_push
  displayName: 'Build and Push'
  dependsOn: unittest
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - script: |
      echo "sha_short=$(Build.SourceVersion)" >> $(Build.SourcesDirectory)/env_vars
    displayName: 'Create image tag'
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerhub-swisspine'
      repository: 'rackylaguerta14/swisspine'
      command: 'buildAndPush'
      tags: |
        $(Build.SourceVersion)
      Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'