name: DevOps Engineering Test
on:
  push:

jobs:
  unittest:
    runs-on: python:3.9.19-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run unittest
        run: python -m unittest unittest/test.py

  build_and_push:
    runs-on: ubuntu-latest
    needs: unittest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create image tag
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: rackylaguerta14/swisspine:${{ env.sha_short }}